name             'dev'
maintainer       'Michael J Jones'
maintainer_email 'meicaljohnjones@gmail.com'
license          'All rights reserved'
description      'Installs/Configures dev'
long_description 'Installs/Configures dev'
version          '0.1.0'

depends 'mysql', '~> 8.2.0'
depends 'mysql2_chef_gem', '~> 1.0'
depends 'database', '~> 6.1.1'
depends 'maven', '~> 4.0.1'